* group_vars/node:

default_folder: /home
default_perms: "0744"
nginx_listen_port: 80
#nginx_server_message: "Handler triggered successfully!"
nginx_server_message: "***** SUCCESS ******"

* templates/nginx.conf.j2:
user www-data;
worker_processes auto;
pid /run/nginx.pid;

events {
    worker_connections 768;
    # multi_accept on;
}

http {
    sendfile on;
    tcp_nopush on;
    tcp_nodelay on;
    keepalive_timeout 65;
    types_hash_max_size 2048;

    include /etc/nginx/mime.types;
    default_type application/octet-stream;

    server {
        listen {{ nginx_listen_port }}  default_server;
        listen [::]:{{ nginx_listen_port }} default_server;

        server_name _;

        location / {
            return 200 '{{ nginx_server_message }}';
        }
    }
}

*  nginx.yaml
ansible_user@2ace93bb7827:~$ cat nginx.yaml
---
- name: Exercice Handlers - Configuration de Nginx sur Ubuntu
  hosts: node
  become: yes

  tasks:
    - name: Installer Nginx
      ansible.builtin.apt:
        name: nginx
        state: present
        update_cache: yes

    - name: Créer un fichier de configuration personnalisé
      template:
        src: templates/nginx.conf.j2
        dest: /etc/nginx/nginx.conf
        owner: root
        group: root
        mode: '0644'
      notify: Redémarrer Nginx

    - name: Démarrer Nginx
      ansible.builtin.service:
        name: nginx
        state: started

  handlers:
    - name: Redémarrer Nginx
      ansible.builtin.service:
        name: nginx
        state: restarted


